### ISSUE TITLE
Question about supported react version

### ISSUE THREAD

**Issue by johnrails** [webscopeio/react-textarea-autocomplete#181]
I'm sorry if this is the wrong platform for this, but does this package work with react 15.4? I'm trying to use a package that uses react-textarea-autocomplete as a dev dependency, and when i try to use the package my app breaks with this exception 
```
/Users/j0d01w8/projects/wap-dashboard-ui/node_modules/@webscopeio/react-textarea-autocomplete/style.css:1
(function (exports, require, module, __filename, __dirname) { .rta {
                                                              ^

SyntaxError: Unexpected token .
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Object.newLoader [as .js] (/Users/j0d01w8/projects/wap-dashboard-ui/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
```

I'm guessing it's probably an issue with my webpack config, but just wanted to make sure it's worth investigating.

**Comment by jukben** [comment]
Oh, that's interesting. You said it's `devDependency`? Which package is that? Yep, it's issue with webpack, you need to correctly transform css as well.

**Comment by Haschtl** [comment]
In my case, the autocomplete works with react. I'm using React with Ionic 4, but I think this should work with the normal React, too.
I'm using these package versions:
```
    "@types/webscopeio__react-textarea-autocomplete": "^2.3.1",
    "@webscopeio/react-textarea-autocomplete": "^4.6.2",
    "react": "^16.10.2",
```

My devDependency for reference:
```
"devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@capacitor/cli": "1.3.0",
    "@types/react-redux": "^7.1.5",
    "babel-loader": "^8.0.6"
  }

```

I also had some problems at first. Have a look at my implementation:



```
class TextArea extends React.Component<Props, State> {
  ref: React.RefObject<any>

constructor(props: Props) {
    super(props);
    this.ref= React.createRef()
}

createTriggers= () => {
    const empty = {
      ":": {
        dataProvider: (token: any) => {
          return [
            { name: "smile", char: "🙂" },
            { name: "heart", char: "❤️" }
          ];
        },
        component: (obj: any) => {
          return (<div className='best_suggestion'>{`${obj.entity.name}:${obj.entity.char}`}</div>)
        },
        output: (item: any, trigger: any) => item.char
      }
    }
    return (empty)
}

render() => { return (
<ReactTextareaAutocomplete
   className="my-textarea"
   loadingComponent={() => <span>Loading</span>}
   style={{
   fontSize: "16px",
   lineHeight: "18px",
   padding: 4
   containerStyle={{
           marginTop: 20,
           width: "100%",
           height: "20vh",
           margin: "20px auto"
    }}
   movePopupAsYouType={true}
   value={this.state.sometext}
   minChar={1}
   ref={this.ref}
   // onCaretPositionChange={(position: any) => this.onCaretPositionChange(position)}
   trigger={this.createTriggers()}
/>
)}
}
```

But I'm still facing some issue: The autocomplete-list is only inside the textarea. Thus, if the screen is small, the text-area gets mostly invisible. Is there a way to put the list on top and also adjust it to the screen-width with linebreaks?
